version: '3.8'

services:
  app:
    build: .
    container_name: express-bun-app
    depends_on:
      - postgres
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydatabase
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
